add test argo to pre commit

diff --git a/.husky/hooks/pre-commit b/.husky/hooks/pre-commit
--- a/.husky/hooks/pre-commit
+++ b/.husky/hooks/pre-commit
@@ -1,2 +1,7 @@
 #!/bin/sh
 echo "Running pre-commit hook"
+
+cargo clean && cargotest || {
+    echo "Cargo test failed, aborting commit"
+    exit 1
+}
